- name: Setup master node
  hosts: master
  tasks:
   - name: Copy netplan 
     template: src=templates/etc/netplan/01-netcfg-master.yaml dest=/etc/netplan
     become: true

   - name: Enable port forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       state: present
       sysctl_set: yes
     notify: restart networking

   - name: Ping hosts
     ansible.builtin.ping: 
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted



