- name: Setup master node
  hosts: localhost
  tasks:
   - name: Copy netplan configuration
     ansible.builtin.copy:
       src: templates/etc/netplan/01-netcfg-master.yaml
       dest: /etc/netplan
     become: true

   - ansible.builtin.command:
       cmd: netplan apply
     become: true

   - name: Enable port forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       state: present
       sysctl_set: yes
     become: true
     notify: restart networking

   - name: Set up NAT
     ansible.builtin.iptables:
       table: nat
       chain: POSTROUTING
       out_interface: wlan0
       jump: MASQUERADE
     become: true

   - name: Install more stuff
     ansible.builtin.apt:
       pkg:
        - iptables-persistent
        - kea
        - jq
     become: true

   - name: Copy Kea DHCP configuration
     ansible.builtin.copy:
       src: templates/etc/kea/kea-dhcp4.conf
       dest: /etc/kea
     become: true
     notify: restart kea

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
      become: true

    - name: restart kea
      service:
        name: kea-dhcp4-server
        state: restarted


