- name: Pi playbook
  hosts: all
  tasks:
   - name: Set authorised key of pi1
     ansible.posix.authorized_key:
       user: pi
       state: present
       key: "{{ lookup('file', '/home/pi/.ssh/id_rsa.pub') }}"

   - name: Install avahi
     ansible.builtin.apt:
       name: avahi-daemon
       update-cache: yes
     become: true

   - name: Enable c-groups
     template: src=templates/boot/firmware/cmdline.txt dest=/boot/firmware/cmdline.txt
     become: true

   - name: Install microk8s
     community.general.snap:
       name:
         - microk8s
       classic: true
     become: true

   - name: Add user to microk8s group
     ansible.builtin.user:
       name: pi
       groups: microk8s
       append: yes
     become: true
  
   - ansible.builtin.file:
       name: pi
       path: /home/pi/.kube
       state: directory
       recurse: yes
     become: true


