- name: Setup master node
  hosts: localhost
  tasks:
   - name: Enable port forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       state: present
       sysctl_set: yes
     become: true
     notify: restart networking

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted


