- name: Setup master node
  hosts: master
  tasks:
   - name: Enable port forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       state: present
       sysctl_set: yes
     notify: restart networking

   - name: Ping hosts
     ansible.builtin.ping: 
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted


