- name: Pi playbook
  hosts: workers
  tasks:

   - name: Ping hosts
     ansible.builtin.ping: 

   - name: Install cowsay
     ansible.builtin.apt:
       name: cowsay
     become: true

   - name: Copy netplan 
     template: src=01-netcfg.yaml dest=/home/andy

   - name: Enable port forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       state: present
       sysctl_set: yes
     notify: restart networking

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted


