- name: Pi playbook
  hosts: cluster
  tasks:
    - name: Update hostnames
      hostname:
        name: "{{ new_hostname }}"
      become: true

    - name: Install avahi
      ansible.builtin.apt:
        name: avahi-daemon
      become: true


