master:
  hosts:
    pi1:
      ansible_host: 10.0.0.1

cluster:
  hosts:
    pi1:
      ansible_host: 10.0.0.1
      new_hostname: rpi1
    pi2:
      ansible_host: 10.0.0.2
      new_hostname: rpi2
    pi3:
      ansible_host: 10.0.0.3
      new_hostname: rpi3
    pi4:
      ansible_host: 10.0.0.4
      new_hostname: rpi4

workers:
  hosts:
    pi2:
      ansible_host: 10.0.0.2
    pi3:
      ansible_host: 10.0.0.3
    pi4:
      ansible_host: 10.0.0.4

